In [1]:
import itertools
import math
import numpy as np

arrays = np.array(list(itertools.permutations(range(10))))

In [2]:
print(arrays[:10])

[[0 1 2 3 4 5 6 7 8 9]
 [0 1 2 3 4 5 6 7 9 8]
 [0 1 2 3 4 5 6 8 7 9]
 [0 1 2 3 4 5 6 8 9 7]
 [0 1 2 3 4 5 6 9 7 8]
 [0 1 2 3 4 5 6 9 8 7]
 [0 1 2 3 4 5 7 6 8 9]
 [0 1 2 3 4 5 7 6 9 8]
 [0 1 2 3 4 5 7 8 6 9]
 [0 1 2 3 4 5 7 8 9 6]]
